# Generated by Django 3.0.3 on 2020-02-26 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del Socio', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del Socio', max_length=100)),
                ('email', models.CharField(help_text='Email del Socio', max_length=100)),
                ('telefono', models.CharField(help_text='Telefono del Socio', max_length=100)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('dni', models.CharField(help_text='DNI del Socio', max_length=15, unique=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Socios',
            },
        ),
    ]
