# Generated by Django 3.0.3 on 2020-02-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='fecha_fin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
