# Generated by Django 3.0.3 on 2020-02-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_auto_20200226_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
